name: Release Please

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      # create release commit
      contents: write
      # create release PR
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: 🆕 Create or update release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  npm-publish:
    needs: [release-please]
    runs-on: ubuntu-latest
    # Only run if a release was created
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - run: echo "Publishing to npm"
